name: playground_dart_webgl
description: A sample dartemis application
dependencies:
  browser: any
  dartemis_toolbox: any
  gamedev_helpers:
    git: https://github.com/denniskaselow/gamedev_helpers
#    path: ../gamedev_helpers
